# Generated by Django 5.2.6 on 2025-10-28 16:52

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=32)),
                ('detail', models.JSONField()),
                ('user_id', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(max_length=32)),
                ('data_store', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='djr_event_user_id_idx'), models.Index(fields=['type'], name='djr_event_type_idx'), models.Index(fields=['status'], name='djr_event_status_idx'), models.Index(fields=['-created_at'], name='djr_event_created_at_idx'), django.contrib.postgres.indexes.GinIndex(fields=['detail'], name='djr_event_detail_gin', opclasses=['jsonb_path_ops']), django.contrib.postgres.indexes.GinIndex(fields=['data_store'], name='djr_event_data_store_gin', opclasses=['jsonb_path_ops'])],
            },
        ),
    ]
