# Generated by Django 5.2.8 on 2025-11-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorealtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('user_id', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='djangorealtime.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', '-created_at'], name='djr_activity_event_created_idx')],
            },
        ),
    ]
